default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  sslmode: require
  connect_timeout: 10
  checkout_timeout: 10

development:
  <<: *default
  host: bcpostgressqlserver12.postgres.database.azure.com
  port: 5432
  database: Docuseal_dev
  username: Vertoxlabs
  password: "Vtx@mru@#5951#new"

test:
  <<: *default
  host: bcpostgressqlserver12.postgres.database.azure.com
  port: 5432
  database: Docuseal_test
  username: Vertoxlabs
  password: "Vtx@mru@#5951#new"

production:
  <<: *default
  host: bcpostgressqlserver12.postgres.database.azure.com
  port: 5432
  database: Docuseal_prod
  username: Vertoxlabs
  password: "Vtx@mru@#5951#new"
